title: GG
author:
  name: Ganesh Gunasegaran
  email: me@itsgg.com

description: >-
  The Architect

copyright: >-
  © Ganesh Gunasegaran

show_excerpts: true

logo: /assets/logo.png

header_pages:
  - about.md

footer_links:
  - title: Twitter
    url: https://twitter.com/itsgg
    icon: fab fa-twitter-square
  - title: GitHub
    url: https://github.com/itsgg
    icon: fab fa-github-square
  - title: Feed
    url: /blog/feed.atom
    icon: fas fa-rss-square

markdown: kramdown

remote_theme: mmistakes/so-simple-theme
skin: "/assets/css/skins/itsgg.css"

mathjax:
  enable: true

feed:
  path: /blog/feed.atom
plugins:
  - jekyll-feed
  - jekyll-remote-theme
  - jekyll-paginate
  - jekyll-relative-links

relative_links:
  enabled: true
  collections: true

search_full_content: true

category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

paginate: 5
paginate_path: /page:num/
